discord:
  client_id: "YOUR_CLIENT_ID"
  secret: "YOUR_CLIENT_SECRET"
  token: "YOUR_BOT_TOKEN"

pocketbase:
  port: 8090

dev:
  enabled: false
  # This will register all slash commands with the guild for instant updates.
  guild_id: "YOUR_DEV_GUILD_ID"
